### ISSUE TITLE
Acquired token in tokens.json file is not found after authentication

### ISSUE THREAD

**Issue by btehan** [ismarslomic/google-assistant-oauth#1] opened 2022-08-26 16:59 UTC
Hello.

I'm trying to use this to make the tokens file and I think that I'm close but I'm running into an issue.
I've got this setup using a portainer stack and the config looks like this:

> version: "3.9"
> services:
> google-assistant-oauth:
>     container_name: google-assistant-oauth
>     image: ismarslomic/google-assistant-oauth:latest
>     ports:
>       - "3005:3005"
>     volumes: 
>       - /home/containers/google-assistant-oauth:/usr/src/config

I've created the client_secret.json file in the /home/containers/google-assistant-oauth directory and copied the content from the client_secret_****.apps.googleusercontent.com.json file into /home/containers/google-assistant-oauth/client_secret.json.

I can start the google-assistant-oauth container and go to it's logs and I get an entry like this:

> Go to this URL in your browser: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fassistant-sdk-prototype&response_type=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

I go to that link and I get a "sign in with Google" page where I see my google account, I click that and hit the continue button.

It then changes to a "http://localhost:3005/oauth2callback?code=xxxxxxxxxxxxxxxxxxxxxxxxx" page that times out.  But if replace the localhost part with the IP address of the LXC where docker is running, then I get this:

> Authentication successful! Please return to the console.

I go back to the logs of the container and see this:

> Tokens acquired.
> Tokens saved to /usr/src/config/tokens.json.

However, I don't see a tokens.json file:

> root@docker:/home/containers/google-assistant-oauth# ls
> client_secret.json
> root@docker:/home/containers/google-assistant-oauth# 

I'm a bit lost here, where am I going wrong?

Thanks!

**Comment by ismarslomic** [comment] 2022-08-26 20:33
That seems strange. You should find the `tokens.json` in the folder `/home/containers/google-assistant-oauth` on your host, when the token has been acquired and saved to the container.

Could you try bypassing Portainer and just execute the docker run command directly from your terminal?

```
docker run --rm \
-p 3005:3005 \
-v /home/containers/google-assistant-oaut:/usr/src/config \
ismarslomic/google-assistant-oauth:latest
```

Make sure that the `client_secret.json` is placed in the folder `/home/containers/google-assistant-oauth` on your host before running the command.

**Comment by btehan** [comment] 2022-08-26 21:28
I'm getting a different issue that way:

> root@docker:/home/containers/google-assistant-oauth# docker run --rm \
> -p 3005:3005 \
> -v /home/containers/google-assistant-oaut:/usr/src/config \
> ismarslomic/google-assistant-oauth:latest
> [ERROR] Client Secret file at path '/usr/src/config/client_secret.json' does not exist.
> root@docker:/home/containers/google-assistant-oauth# sudo docker run --rm -p 3005:3005 -v /home/containers/google-assistant-oaut:/usr/src/config ismarslomic/google-assistant-oauth:latest
> [ERROR] Client Secret file at path '/usr/src/config/client_secret.json' does not exist.
> root@docker:/home/containers/google-assistant-oauth# ls
> client_secret.json
> root@docker:/home/containers/google-assistant-oauth# 
> root@docker:/home/containers/google-assistant-oauth# cat client_secret.json 
> {"installed":{"client_id":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

> root@docker:/home/containers/google-assistant-oauth# ls -lh
> total 4.5K
> -rw-r--r-- 1 root root 402 Aug 26 11:28 client_secret.json
> root@docker:/home/containers/google-assistant-oauth# whoami
> root
> root@docker:/home/containers/google-assistant-oauth#

**Comment by btehan** [comment] 2022-08-26 21:57
Just to be safe, I've gone back through [broadcast issue #7](https://github.com/ismarslomic/google-assistant-broadcast/issues/7) and I'm pretty sure my client_secret.json is correct:



> {"installed":{"client_id":"xxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com","project_id":"xxxxx-xxxx","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","redirect_uris":["http://localhost"]}}

**Comment by ismarslomic** [comment] 2022-09-04 21:03
I'm sorry, but this issue is not related to the docker image but with your local Docker installation. I have tested this image on Ubuntu, Raspberry pi OS and OSX and can't reproduce it. Closing this issue for now. But please add a comment if you find solution, so it can help other users.

**Closed as completed by ismarslomic** 2022-09-04 21:03 UTC
Labels: question

**Comment by clehmann** [comment] 2022-12-01 17:55
I had a similar issue using docker in ubuntu 2022.04. Ended up being a permissions issue, had to pass `--privileged` to the docker command
